services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./server:/app